### PR TITLE
fix: update the existing_subnet_names variable description

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — APPROVED** [review]

**Comment by ocofaigh** [comment]
Pipeline failed with:
```
Error: [0m Error: [ERROR] VPNServer failed Error Getting VPC Server: Get "https://eu-de.iaas.cloud.ibm.com/v1/vpn_servers/r010-aceb7e04-8dda-43f5-b6bb-4e2548498e1e?generation=2&version=2023-10-17": context deadline exceeded
│ null
│ 
│ 
│ 
│   with module.vpn.ibm_is_vpn_server.vpn,
│   on ../../main.tf line 58, in resource "ibm_is_vpn_server" "vpn":
│   58: resource "ibm_is_vpn_server" "vpn" {
│ 
╵}
```

Retrying..

**Comment by ocofaigh** [comment]
Hmm, pipeline failed again with:
```
Error: [0m Error: [ERROR] VPNServer failed The VPC route r026-0272dc84-e4a2-42db-b1c1-2631b39604eb failed to delete: Get "https://au-syd.iaas.cloud.ibm.com/v1/vpn_servers/r026-0272dc84-e4a2-42db-b1c1-2631b39604eb?generation=2&version=2023-08-08": context deadline exceeded
```

I'll try again..

**Comment by Aashiq-J** [comment]
I was not able to re-create the issue in local.

**Pull request merged**
