### PR TITLE
fix: fix issue preventing destroy of vpn routes + cleanup

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

Fixes:
- Fixed incorrect depends_on which was causing vpn route deletion to fail
- Updated some variable descriptions

CI changes:
- Migrated CRA config to cra-config.yaml
- Removed `Brewfile` (Brew no longer used by CI)

Doc changes:
- Added meatadata to readme for new overview hook
- usage cleanup
- removed catalogValidationValues.json.template (not used)

Examples:
- Added basic example (standalone vpn locked into modules lowest supported ibm provider version - 1.54.0)
- Set up the HA example to use latest provider version
- removed restapi provider config - provider is not used
- updated to use secrets-manager-secret-group module
- locked slz extension example into 1.54.0 since its designed to be imported as a DA
- Added lifecycle ignore changes to SLZ example to address https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4721

Tests:
- Run basic example in other_test.go
- HA example (standard and upgrade) in pr_test.go
- Set up an end to end test for testing the SLZ example (NOTE: It currently has a workaround in it (retry the destroy) due to known provider issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4722)

NOTE: The upgrade test had to be skipped in this PR due to the directory of the example being renamed. This is low risk since the changes to the module code itself are very small.

#### Changes that affect the core Terraform module or submodules
- [x] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [x] Examples or tests (addition or updates of examples or tests)
- [x] Documentation update
- [x] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.

Your notes help the merger write the commit message for the PR that is published in the release notes for the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Review by jor2 — DISMISSED** [review]

**Comment by ocofaigh** [comment]
Ah I added the retry to the wrong destroy.. let me see how I can add the workaround to the correct state

**Review by jor2 — APPROVED** [review]

**Pull request merged**
