### PR TITLE
chore: update version constraints

### PR DESCRIPTION
**Pull request by iamar7**
### Description

update version constraints

https://github.ibm.com/GoldenEye/issues/issues/4915

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by iamar7** [comment]
> @iamar7 Was there a reason why you bumped minimum from `">= 1.57.0, < 2.0.0"` -> `">= 1.59.0, < 2.0.0"` ?

I have updated the version from `1.57.0` to `1.61.0` because while initializing provider plugins the pre-commit was failing giving the following error:

```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ ibm-cloud/ibm: no available releases match the given constraints >= 1.49.0,
│ >= 1.51.0, >= 1.57.0, 1.57.0, >= 1.59.0, >= 1.61.0, < 2.0.0
```

**Comment by ocofaigh** [comment]
OK it means our basic example has a dependant module that requires `>= 1.61.0` so hence we can't lock it into `1.57.0`. Lets go with this for now, I'll be discussing an item on our next deep dive around handling provider versions going forward anyway

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
