### PR TITLE
fix: reference architecture image fix

### PR DESCRIPTION
**Pull request by rajatagarwal-ibm**
### Description

Fixes image in dark and light theme

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by rajatagarwal-ibm** [comment]
Light theme:

image

Dark theme:
image

**Comment by ocofaigh** [comment]
@rajatagarwal-ibm Looks like one of the icons isn't displaying:
image

Also [this PR](https://github.com/terraform-ibm-modules/terraform-ibm-client-to-site-vpn/pull/153) should be merged first, can you please review it?

**Comment by rajatagarwal-ibm** [comment]
Updated user with the white background:

Light theme:
image


Dark theme:
image

**Comment by SirSpidey** [comment]
make sure that you use the ibm version of draw.io (not diagrams.net) and are following the guidance for creating technical diagrams and exporting SVGs.

https://test.cloud.ibm.com/docs-internal/writing?topic=writing-diagrams#diagrams-drawio

**Comment by rajatagarwal-ibm** [comment]
@SirSpidey Thanks, I just made this diagram compatible with dark and light themes as part of this issue. But let me update the issue to migrate this from the "diagrams.net" to the "draw.io" version, and work on it.

**Comment by SirSpidey** [comment]
> @SirSpidey Thanks, I just made this diagram compatible with dark and light themes as part of this issue. I see you have already created an issue for that, let me address migration from the "diagrams.net" to the "draw.io" version in this same PR.

@rajatagarwal-ibm I created https://github.ibm.com/GoldenEye/issues/issues/6854 for that.

**Comment by rajatagarwal-ibm** [comment]
Updated diagram (with white background as suggested by Allen)

**Light theme:**
image

**Dark theme:**
image

**Review by SirSpidey — APPROVED** [review]

**Pull request merged**
